# -*- coding: utf-8 -*-
"""cars2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15870t6EU2A_JoGBZrxfDcu4bmW5V0k6R
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
from PIL import Image
logo = Image.open('logo1.png')
#pip install pandas numpy matplotlib seaborn streamlit
#to run strealit :   streamlit run test2.py 
st.set_page_config(page_title=" CARS EDA", page_icon=":bar_chart:", layout="wide")
st.image(logo)
st.title("𝙴𝚇𝙿𝙻𝙾𝚁𝙰𝚃𝙾𝚁𝚈 𝙳𝙰𝚃𝙰 𝙰𝙽𝙰𝙻𝚈𝚂𝙸𝚂 (𝙴𝙳𝙰)")
# File upload
uploaded_file = st.file_uploader("𝚄𝙿𝙻𝙾𝙰𝙳 𝙰 𝙲𝙰𝚁𝚂 𝙳𝙰𝚃𝙰 𝚂𝙴𝚃 :")
if uploaded_file is not None:
    data=pd.read_csv(uploaded_file)
    st.dataframe(data)
    names = ["𝟸𝟷𝙰𝟸𝟷𝙰𝟼𝟷𝟷𝟹 – 𝙶 𝙺 𝙱𝙷𝙰𝚂𝙺𝙰𝚁","𝟸𝟷𝙰𝟸𝟷𝙰𝟼𝟷𝟹𝟹 – 𝙻 𝙷𝙰𝚁𝚂𝙷𝙰 𝚅𝙰𝚁𝙳𝙷𝙰𝙽","𝟸𝟷𝙰𝟸𝟷𝙰𝟼𝟷𝟶𝟾 – 𝙶 𝚂𝚆𝙰𝚁𝚄𝙿𝙰","𝟸𝟷𝙰𝟸𝟷𝙰𝟼𝟷𝟸𝟶 – 𝙺 𝙿𝚁𝙰𝚂𝙰𝙳","𝟸𝟷𝙰𝟸𝟷𝙰𝟼𝟷𝟸𝟾 – 𝙺 𝚂𝙷𝚈𝙰𝙼𝙰𝙻𝙰","𝟸𝟷𝙰𝟸𝟷𝙰𝟼𝟷𝟷𝟶 – 𝙳 𝚂𝙷𝚈𝙰𝙼","𝟸𝟷𝙰𝟸𝟷𝙰𝟼𝟷𝟸𝟸 – 𝙺 𝚄𝙼𝙰 𝚂𝙰𝙸","𝟸𝟶𝙰𝟸𝟷𝙰𝟼𝟷𝟶𝟾 – 𝙱 𝚂𝙰𝙸 𝚁𝙰𝙼"]
    st.sidebar.title("𝙿𝚁𝙾𝙹𝙴𝙲𝚃 𝚃𝙴𝙰𝙼 𝙼𝙴𝙼𝙱𝙴𝚁𝚂 :")

    for name in names:
        st.sidebar.write(name)

    st.sidebar.title("𝚄𝙽𝙳𝙴𝚁 𝚃𝙷𝙴 𝙶𝚄𝙸𝙳𝙴𝙽𝙲𝙴 𝙾𝙵 :")
    st.sidebar.write(" 𝙳𝚁 𝙱𝙾𝙼𝙼𝙰 𝚁𝙰𝙼𝙺𝚁𝙸𝚂𝙷𝙽𝙰")
    st.title("𝙲𝙰𝚁𝚂 𝙳𝙰𝚃𝙰 𝙰𝙽𝙰𝙻𝚈𝚂𝙸𝚂")
    if st.checkbox("𝚁𝙰𝚆 𝙳𝙰𝚃𝙰 :"):
        st.write(data)
    if st.checkbox("RAW DATA INFO :"):
      st.write("NULL VALUES IN EACH COLUMN :")
      st.write(data.isnull().sum())
    if st.checkbox("DATA CLEANING OR PREPROCESIONG :"):
      data=data.dropna()
      st.write(data)
    if st.checkbox("DATA INFO AFTER CLEANING :"):
      st.write("NULL VALUES IN EACH COLUMN :")
      st.write(data.isnull().sum())      
    if st.checkbox("𝚂𝙷𝙾𝚆 𝙵𝙸𝚁𝚂𝚃 𝟸𝟻 𝚁𝙾𝚆𝚂 :"):
        st.write(data.head(25))

    if st.checkbox(" 𝚂𝙷𝙾𝚆 𝚂𝙷𝙰𝙿𝙴 :"):
        st.write("SHAPE :",data.shape)
        
    if st.checkbox("BASIC DETAILS ABOUT MANUFACTURERS :"):
        if st.checkbox("DIFFERENT TYPES OF MANUFACTURERS AND THIER COUNTS :"):
          st.write(data['Make'].value_counts())

        if st.checkbox("𝙼𝙰𝙽𝚄𝙵𝙰𝙲𝚃𝚄𝚁𝙴𝚁  𝚆𝙷𝙾 𝙿𝚁𝙾𝙳𝚄𝙲𝙴𝚂 𝚂𝙴𝙳𝙰𝙽 𝙼𝙾𝙳𝙴𝙻 𝙲𝙰𝚁𝚂 :"):
            data1=data.where(data['Type']=='Sedan')['Make'].unique()
            st.write(data1[1:])
        if st.checkbox("𝙼𝙾𝙳𝙴𝙻 𝚃𝚈𝙿𝙴 𝚃𝙾 𝙲𝙷𝙴𝙲𝙺 𝚃𝙷𝙴 𝙼𝙰𝙽𝚄𝙵𝙰𝙲𝚃𝚄𝚁𝙴𝚁𝚂 :"):
            st.write("PLEASE CHOOSE MODELS FROM THE ABOVE LIST :",data['Type'].unique())
            x=st.text_input("PLEASE ENTER MODEL TYPE :")
            data1=data.where(data['Type']==x)['Make'].unique()
            st.write(data1[1:])
        if st.checkbox("SHOW ALL THE RECORDS ARE ORIGIN IN EUROPE OR ASIA"):
          st.write(data[data['Origin'].isin(['Asia', 'Europe'])])
          st.write(data['Origin'].value_counts())
    if st.checkbox("SHOW DATA VISULIAZATIONS "):
      if st.checkbox("HISTOGRAM THAT SHOWS COUNT OF DIFFERENT MAKES "):
        fig, ax = plt.subplots()
        sns.histplot(data=data, x="Make", ax=ax)
        ax.set_xlabel("MAKE")
        ax.set_ylabel("Count")
        # Display histogram
        st.pyplot(fig)
      if st.checkbox("SCATTER PLOT"):
        fig, ax = plt.subplots()
        a=data['MSRP'].unique()
        b=data['Invoice'].unique()
        sns.scatterplot(data=data, x='a', y='b', ax=ax)
        ax.set_xlabel("MSRP")
        ax.set_ylabel("Invoice")
        # Display scatterplot
        st.pyplot(fig)
